name: docs/gh-pages
on: workflow_dispatch

jobs:
    build-docs:
        name: Build docs and push to gh-pages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Setup python 
              uses: actions/setup-python@master
              with:
                python-version: 3.8
            
            - name: Install poetry
              uses: snok/install-poetry@v1.3.3
              with:
                version: 1.2.2
                virtualenvs-create: true
                virtualenvs-in-project: true
                installer-parallel: true
            
            - name: Install dependencies
              run: |
              source $HOME/.poetry/env
              poetry install
            
            - name: build docs
              run: |
                source .venv/bin/activate 
                cd docs
                make clean
                make html
                cd ..

            - name: deploy to gh-pages
              uses: Cecilapp/GitHub-Pages-deploy@v3
              env:
                GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              with:
                email: david.hagan@quant-aq.com
                build_dir: docs/_build/html
